# Generated by Django 2.2.2 on 2019-07-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('template', models.CharField(default='page/index.html', max_length=200, verbose_name='Активность')),
                ('slug', models.SlugField(max_length=60, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
