# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('mini_text', models.TextField(max_length=600, verbose_name='Превью статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка статей')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Просмотрено')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
