# Generated by Django 2.2.2 on 2019-07-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=30, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Телефон'),
        ),
    ]
