# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('slug', models.SlugField(max_length=60, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sort',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Сортировка статей'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Теги'),
        ),
    ]
