# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190622_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800, verbose_name='текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('moderation', models.BooleanField(default=True, verbose_name='Разрешена модерация')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=60, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post', verbose_name='Пост'),
        ),
    ]
