# Generated by Django 2.2.2 on 2019-07-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190708_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
