# Generated by Django 2.2.2 on 2019-07-16 18:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('is_auth', models.BooleanField(default=False, max_length=30, verbose_name='Для зарегистрированныых')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='ItemsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название на латинице')),
                ('title', models.CharField(max_length=30, verbose_name='Название на кириллице')),
                ('status', models.BooleanField(default='True', verbose_name='Отображение')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Для залогиненых')),
                ('anchor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Якорь')),
                ('url', models.TextField(verbose_name='Ссылка на внешний ресурс')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.ItemsMenu')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
